# Generated by Django 5.2.15 on 2026-06-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novel",
            name="genres",
            field=models.ManyToManyField(related_name="novels", to="core.genre"),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(fields=("novel", "lexorank"), name="uq_novel_lexorank"),
        ),
    ]
