# Generated by Django 5.2.15 on 2026-07-03 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_readingprogress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="chapter",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="chapter",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="fileasset",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="novel",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="novel",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="novel",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.CreateModel(
            name="NovelReadEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("viewer_id", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "novel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="read_events", to="core.novel"
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("novel", "viewer_id"), name="uq_novel_viewer")],
            },
        ),
    ]
