# Generated by Django 5.2.15 on 2026-07-03 11:25

from django.db import migrations, models


def backfill_last_publication_at(apps, schema_editor):
    Novel = apps.get_model("core", "Novel")
    Chapter = apps.get_model("core", "Chapter")
    for novel in Novel.objects.all():
        latest = Chapter.objects.filter(novel=novel, is_published=True).aggregate(latest=models.Max("published_at"))[
            "latest"
        ]
        if latest:
            novel.last_publication_at = latest
            novel.save(update_fields=["last_publication_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_created_chapter_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="novel",
            name="last_publication_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.RunPython(backfill_last_publication_at, migrations.RunPython.noop),
    ]
