# Generated by Django 5.2.15 on 2026-07-04 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_novel_last_chapter_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="readingprogress",
            name="uq_user_novel",
        ),
        migrations.AddConstraint(
            model_name="readingprogress",
            constraint=models.UniqueConstraint(fields=("user", "novel"), name="uq_readingprogress_user_novel"),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="novel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="bookmarks", to="core.novel"
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="bookmarks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(fields=("user", "novel"), name="uq_bookmark_user_novel"),
        ),
    ]
