# Generated by Django 6.0.6 on 2026-06-04 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=150, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=150, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(null=True)),
                ('deleted_by', models.CharField(max_length=150, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=150, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=150, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(null=True)),
                ('deleted_by', models.CharField(max_length=150, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(related_name='departments', through='sample.UserDetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
