# Generated by Django 6.0.6 on 2026-06-08 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=150, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=150, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(null=True)),
                ('deleted_by', models.CharField(max_length=150, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready')], db_index=True, default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('field_name', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='sample.fileasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=150, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=150, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(null=True)),
                ('deleted_by', models.CharField(max_length=150, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(related_name='departments', through='sample.UserDetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
