# Generated by Django 6.0.6 on 2026-06-08 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready')], db_index=True, default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('field_name', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='sample.fileasset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
