# Generated by Django 6.0.6 on 2026-06-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_fileasset_fileattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='content_type',
            field=models.CharField(default='*/*', max_length=255),
            preserve_default=False,
        ),
    ]
